name: Checks

on:
  push:
    branches:
    - dev
  workflow_call:
  workflow_dispatch:

jobs:
  checks:
    name: "Run Checks"
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/restore-or-build
      name: "Restore or build"
      with:
        build_env: dev
    - name: Source formatting
      id: formatting
      if: always()
      run: mix format --dry-run --check-formatted
    - name: Unused deps
      id: unused-deps
      if: always()
      run: mix deps.unlock --check-unused
    - name: Retired Hex deps
      id: audit-deps
      if: always()
      run: mix hex.audit
    - name: Credo high priority checks
      id: credo
      if: always()
      run: mix credo --min-priority high
